# Generated by Django 6.1 on 2026-09-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='categoria',
            field=models.CharField(choices=[('corte', 'Corte / Cabelo'), ('manicure', 'Manicure / Pedicure'), ('tratamento', 'Tratamento Capilar'), ('coloracao', 'Coloração'), ('sobrancelha', 'Sobrancelha / Cílios'), ('estetica', 'Estética Facial')], max_length=20),
        ),
    ]
